### PR TITLE
fix: broken how-retro-funding-works's link

### PR DESCRIPTION
**Pull request by AdventureSeeker987**

### CODE REVIEW

**Review by kittybest — APPROVED** [review]
Thanks!

**Review by 0xmad — CHANGES_REQUESTED** [review]
@AdventureSeeker987 thanks, please fix typo in commit message

**Comment by AdventureSeeker987** [comment]
> @AdventureSeeker987 thanks, please fix typo in commit message

@0xmad  fixed

**Comment by 0xmad** [comment]
@AdventureSeeker987 and keep only one commit (without merge commit)
We use rebase for branch updates

**Review by 0xmad — COMMENTED** [review]
@AdventureSeeker987 thanks!

**Review by 0xmad — APPROVED** [review]

**Pull request merged**
